Resolve Atom / Platform IO build errors by changing to v1.8.0
.piolibdeps\ESP Async WebServer\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified()':
.piolibdeps\ESP Async WebServer\src\WebHandlers.cpp:78:25: error: 'time' was not declared in this scope
if(time(&last_modified) == 0) //time is not yet set
^
*** [.pioenvs\wire\lib764\ESP Async WebServer\WebHandlers.cpp.o] Error 1
 [ERROR] Took 7.74 seconds
Environment wire        [ERROR]